### PR TITLE
[Update] Firebase for iOS v5.8.1

### PR DESCRIPTION
**Pull request by SotoiGhost**
This marks the start of the update process.

### CODE REVIEW

**Comment by SotoiGhost** [comment]
This Pull Request contains the following updates:

* [ ] Firebase.Core v5.1.2
* [ ] Firebase.Analytics v5.1.1
* [ ] Firebase.DynamicLinks v3.0.2
* [ ] Firebase.PerformanceMonitoring v2.1.1
* [ ] Firebase.RemoteConfig v3.0.1
* [ ] Firebase.AdMob v7.32.0
* [ ] Firebase.Auth v5.0.3
* [ ] Firebase.CloudFirestore v0.13.2
* [ ] Firebase.CloudMessaging v3.1.1
* [ ] Firebase.Storage v3.0.1
* [ ] Google.SignIn v4.2.0
* [ ] Google.TagManager v7.1.1

**Comment by SotoiGhost** [comment]
@dalexsoto [Firebase.RemoteConfig][1] is ready for review. Thanks bro!

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/pull/182/commits/74bb6e14201207ffc4eadae3b05a56350d6ec8cf#diff-5a98db42b0a9851996dae6c868775551

**Comment by dalexsoto** [comment]
LGTM so far 👍

**Comment by SotoiGhost** [comment]
@dalexsoto [Firebase.Auth][1] is ready for review. Thank you!

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/pull/182/commits/f87f8fa9411e61bc4d94c58e0a9a1af83a9dc895#diff-5623da69229c4dc2352821c3e6771f58

**Comment by SotoiGhost** [comment]
@dalexsoto [Firebase.CloudFirestore][1] is ready for review. Thanks dude!

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/pull/182/commits/f1609189af0abef5e618294eb54864ae971f052c#diff-85afcd023282c2677199761efeafc9e3

**Comment by SotoiGhost** [comment]
@dalexsoto [Firebase.CloudMessaging][1] is ready for review. Thanks bro!

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/pull/182/commits/d84f473b59755cae707377e5c639e9841b6e3360#diff-39b187ec4617f6bd7b8a4f631b826bd5

**Pull request merged**
