### PR TITLE
Firebase 3.15.0

### PR DESCRIPTION
**Pull request by SotoiGhost**
* Firebase.InstanceID
    * Updated to version 1.0.9.0
* Firebase.Core
    * Updated to version 3.5.2.0
* Firebase.Analytics
    * Updated to version 3.7.0.0
* Firebase.AdMob
    * Updated to version 7.19.0.0
* Firebase.Auth
    * Updated to version 3.1.1.0
* Firebase.CrashReporting
    * Updated to version 1.1.6.0
* Firebase.Database
    * Updated to version 3.1.2.0
* Firebase.DynamicLinks
    * Updated to version 1.3.4.0
* Firebase.CloudMessaging
    * Updated to version 1.2.2.0
* Firebase.RemoteConfig
    * Updated to version 1.3.4.0
* Firebase.Storage
    * Updated to version 1.1.0.0
* Google.SignIn
    * Updated to version 4.0.2.0
* Firebase.Invites
    * Updated to version 1.2.5.0

### CODE REVIEW

**Comment by kimdv** [comment]
@SotoiGhost does this update support Firebase phone auth? :)

**Comment by SotoiGhost** [comment]
@kimdv Not yet, we will support that in the next release.

**Comment by kimdv** [comment]
@SotoiGhost any timeline for that?
Because Digits will soon close :)

**Comment by SotoiGhost** [comment]
@kimdv We don't have any ETA yet, but the update is a high priority.

**Pull request merged**
