### PR TITLE
[Update] Firebase for iOS v8.10.0 & MLKitVision

### PR DESCRIPTION
**Pull request by dmariogatto**
Previous PRs:  #495, #494, #489, #485, #479

### Firebase

- All projects updated 8.10.0
- MLKit for Firebase packages deprecated/removed (no longer supported)
   - `Firebase.MLKit`
   - `Firebase.MLKit.Common`
   - `Firebase.MLKit.ModelInterpreter`
   - `Firebase.MLKit.NaturalLanguage`
   - `Firebase.MLKit.Vision`
- Added beta binding for Firebase App Distribution (`Firebase.AppDistribution`) & App Check (`Firebase.AppCheck`)
   - excluded for now (no sample or testing done)
- Minimum iOS version increased to 10.0

### Google

- AdMob updated to 8.13.0
- Google Analytics updated to 3.20.0
- Google Cast updated to 4.7.0
- Google Maps updated to 6.0.1
- Google Places updated to 6.0.0
- Google Tag Manager updated to 7.4.0
- Deprecated/removed packages (due to outdated Firebase dependencies),
   - `Google.AppIndexing`
   - `Google.Core`
   - `Google.InstanceID`
   - `Firebase.InstanceID`
- Minimum iOS version increased to 10.0 (due to Firebase dependencies)

## Google MLKit

Added a new component category `MLKit` with new bindings for the below,

- Common libraries
   - `MLKit.Core` 5.0.0
   - `MLKit.TextRecognition` 1.4.0-beta3
   - `MLKit.Vision` 3.0.0
- [Text Recognition v2](https://developers.google.com/ml-kit/vision/text-recognition/v2/ios)
   - `MLKit.TextRecognition` 1.4.0-beta3
   - `MLKit.TextRecognition.Latin` 1.0.0-beta3
   - `MLKit.TextRecognition.Chinese` 1.0.0-beta3
   - `MLKit.TextRecognition.Devanagari` 1.0.0-beta3
   - `MLKit.TextRecognition.Japanese` 1.0.0-beta3
   - `MLKit.TextRecognition.Korean` 1.0.0-beta3
- [Face Detection](https://developers.google.com/ml-kit/vision/face-detection/ios)
   - `MLKit.FaceDetection` 1.5.0
- [Barcode Scanning](https://developers.google.com/ml-kit/vision/barcode-scanning/ios)
   - `MLKit.BarcodeScanning` 1.6.0
- [Image Labeling](https://developers.google.com/ml-kit/vision/image-labeling/ios)
   - `MLKit.ImageLabeling` 1.5.0
- [Object Detection & Tracking](https://developers.google.com/ml-kit/vision/object-detection/ios)
   - `MLKit.ObjectDetection` 1.5.0
- [Digital Ink Recognition](https://developers.google.com/ml-kit/vision/digital-ink-recognition/ios)
   - `MLKit.DigitalInkRecognition` 1.5.0

## Notes

Removed the `Wrap` methods/properties that where marked as `Obsolete` (seems like a major version bump is the time to do it 😅).

Added a new build property that can be used to link Firebase with/without Ad ID support.

```xml
<PropertyGroup>
  <FirebaseWithoutAdIdSupport>True</FirebaseWithoutAdIdSupport>
</PropertyGroup>
```

There were quite a few binding changes, so would definitely appreciate someone to look them over. All the samples do run & link as far as I can tell.

UMP has been separated out from AdMob (`Google.UserMessagingPlatform`).

Any issues let me know!

### CODE REVIEW

**Comment by mayhammf** [comment]
@dmariogatto Thank you for keeping these PRs coming. 
Do you know if there is a reason they are not getting reviewed/approved by the team?

**Comment by dmariogatto** [comment]
@mayhammf Unfortunately I do not.

My own speculation is these binding libraries are not a priority for Microsoft, and from what I gather the teams that work on Xamarin/MAUI are short-staffed & don't have the time/resources to maintain these projects. Which isn't ideal as I'd regard binding important ecosystem libraries, such as Firebase, as critical to the long-term success of the platform.

For now, I'll continue to update the bindings with new versions & hopefully it will make the team's job a little easier whenever they get time to look at it.

**Comment by SotoiGhost** [comment]
@dmariogatto Thank you for this amazing effort and amazing work! 🎉🎉🎉

I'm planning to start reviewing this ASAP, do you have any WIP that I should wait to be merge??

**Comment by dmariogatto** [comment]
@SotoiGhost

Might as well go with the latest 😀, I've just pushed a new branch [firebase-891](https://github.com/dmariogatto/GoogleApisForiOSComponents/tree/firebase-891)  (including _Maps 5.2_, _Places 5.1_, _Cast 4.7_ & _AdMob 8.13_). Shall I create a new PR, or merge into this branch?

Additionally, I just recently created bindings & a sample for the below GoogleML libraries.

- [Text Recognition v2](https://developers.google.com/ml-kit/vision/text-recognition/v2/ios)
- [Face Detection](https://developers.google.com/ml-kit/vision/face-detection/ios)
- [Barcode Scanning](https://developers.google.com/ml-kit/vision/barcode-scanning/ios)
- [Image Labeling](https://developers.google.com/ml-kit/vision/image-labeling/ios)
- [Object Detection & Tracking](https://developers.google.com/ml-kit/vision/object-detection/ios)
- [Digital Ink Recognition](https://developers.google.com/ml-kit/vision/digital-ink-recognition/ios)

[firebase-891-mlkitvision](https://github.com/dmariogatto/GoogleApisForiOSComponents/tree/firebase-891-mlkitvision) - this can be merged along with the Firebase update to 8.9.1, or separately later.

**Comment by SotoiGhost** [comment]
@dmariogatto Feel free to merge it here. Please, let me know when ready. Thank you!

**Comment by dmariogatto** [comment]
@SotoiGhost Done 🚀

**Comment by dmariogatto** [comment]
@SotoiGhost

You should also be aware that some of the new archive files are deeply nested and run into max path length errors on Windows when extracted by XBD. I have already made a PR, https://github.com/xamarin/XamarinComponents/pull/1296, addressing the issue.

**Comment by dmariogatto** [comment]
@SotoiGhost I've bumped Firebase to 8.10.0, as well as, Google Maps/Places to 6.0.0.

Additionally, as per my comment above XBD has been updated to 0.11.0.

**Pull request merged**
