### PR TITLE
[Update] Firebase for iOS v8.0.0

### PR DESCRIPTION
**Pull request by dmariogatto**
### Firebase

- All projects updated 8.0.0
- MLKit for Firebase packages deprecated/removed (no longer supported)
   - `Firebase.MLKit`
   - `Firebase.MLKit.Common`
   - `Firebase.MLKit.ModelInterpreter`
   - `Firebase.MLKit.NaturalLanguage`
   - `Firebase.MLKit.Vision`
   - _Note: probably need a new project/repo for the newer [Google ML Kit](https://developers.google.com/ml-kit/migration/ios) bindings_
- Added beta binding for Firebase App Distribution (`Firebase.AppDistribution`) & App Check (`Firebase.AppCheck`)
   - excluded for now (no sample or testing done)
- Minimum iOS version increased to 10.0

### Google

- AdMob updated to 8.5.0
- Google Cast updated to 4.6.1
- Google Maps & Places updated to 5.0.0
- Google Tag Manager updated to 7.3.1
- Deprecated/removed packages (due to outdated Firebase dependencies),
   - `Google.AppIndexing`
   - `Google.Core`
   - `Google.InstanceID`
   - `Firebase.InstanceID`
- Minimum iOS version increased to 10.0 (due to Firebase dependencies)

## Notes

Removed the `Wrap` methods/properties that where marked as `Obsolete` (seems like a major version bump is the time to do it 😅).

Added a new build property that can be used to link Firebase with Ad Id support.

```xml
<PropertyGroup>
  <FirebaseWithoutAdIdSupport>True</FirebaseWithoutAdIdSupport>
</PropertyGroup>
```

There were quite a few binding changes, so would definitely appreciate someone to look them over. All the samples do run & link as far as I can tell.

UMP has been separated out from AdMob (`Google.UserMessagingPlatform`).

Any issues let me know!

### CODE REVIEW

**Comment by mayhammf** [comment]
@dmariogatto thank you so much for working on this. 
I just wanna mention that we've used your branch 711 to produce locally built firebase package (with v7.11) and were able to release a build (with FirebaseWithoutAdIdSupport=true) and Apple has approved all of our apps without any issues concerning the tracking transparency stuff.

**Comment by mayhammf** [comment]
We did have to cleanup some of the project refs in the .sln file to get it to build in Visual Studio. 
This PR here includes the projects in question
https://github.com/dmariogatto/GoogleApisForiOSComponents/pull/1/commits/3c828b797bea1af0321a1ceb0644d31443c6d401

**Comment by dmariogatto** [comment]
@mayhammf Glad it's helped!

I didn't notice that PR, I'll review and merge it into this branch.

**Comment by mayhammf** [comment]
On a different note @dmariogatto 
I noticed you wrote the description of this PR that Firebase.InstanceID has been deprecated/removed.
Do you think it still needs to be referenced by Firebase.CloudMessaging?
https://github.com/xamarin/GoogleApisForiOSComponents/blob/8d35520f81534fb009d25347488e4acff973395c/source/Firebase/CloudMessaging/CloudMessaging.csproj#L77

**Comment by dmariogatto** [comment]
@mayhammf `InstanceID` was removed as a dependency from `Messaging` in 8.0.0. You can see the difference in the _"dependencies"_ section of the podspec files - [7.11.0](https://github.com/CocoaPods/Specs/blob/master/Specs/2/d/6/FirebaseMessaging/7.11.0/FirebaseMessaging.podspec.json) & [8.0.0](https://github.com/CocoaPods/Specs/blob/master/Specs/2/d/6/FirebaseMessaging/8.0.0/FirebaseMessaging.podspec.json).

**Comment by mayhammf** [comment]
> @mayhammf `InstanceID` was removed as a dependency from `Messaging` in 8.0.0. You can see the difference in the _"dependencies"_ section of the podspec files - [7.11.0](https://github.com/CocoaPods/Specs/blob/master/Specs/2/d/6/FirebaseMessaging/7.11.0/FirebaseMessaging.podspec.json) & [8.0.0](https://github.com/CocoaPods/Specs/blob/master/Specs/2/d/6/FirebaseMessaging/8.0.0/FirebaseMessaging.podspec.json).

Thank you @dmariogatto for taking the time to reply. I noticed that i was looking at the wrong branch after i posted my question. That's why i ended up deleting it. But it was too later already 😇

**Comment by dtaylorus** [comment]
@dmariogatto This repo appears to be abandoned. Any chance you would publish the nugets from your branch?

**Comment by dmariogatto** [comment]
@dtaylorus  I'd rather leave that as a last resort, it would fragment Firebase packages/documentation/samples. I don't really want to be the sole maintainer either, I can't commit that I'll always have the time/knowledge to keep this repo up-to-date.

I'll continue updating the bindings while I can & creating PRs. Hopefully at some point they will get reviewed, or there will be some indication if this repo is truly abandoned (or possibly just side-lined while teams are busy with MAUI & .NET 6).

**Comment by dtaylorus** [comment]
@dmariogatto Fair enough. In the meantime your branch is super helpful. Thanks! I submitted a pull request to your branch for some fixes required to use rewarded and adaptive banner ads.

**Comment by dmariogatto** [comment]
Now obsolete, see #489

**Pull request closed without merging**
