### PR TITLE
[Google][Cast] Update to target the GoogleCast IOS SDK v4.4.2

### PR DESCRIPTION
**Pull request by Obelobel**
Updated to Target the lastest GoogleCast IOS SDK.

### CODE REVIEW

**Comment by david-laundav** [comment]
@SotoiGhost and @bholmes, could you please review this PR so that we can update the package and thus include some nice new fixes in version 4.3.2.0? Thanks.

**Comment by bholmes** [comment]
This update seems straight forward enough.  @SotoiGhost, can you review and confirm that there are no API changes?

**Comment by SotoiGhost** [comment]
@Obelobel There are some changes between versions. It would be nice if you can add them before we merge it. Thanks in advance!

**Comment by Obelobel** [comment]
Hey @SotoiGhost  and @bholmes is there anything still missing for this to be merged?

**Pull request closed without merging**
